version: '3.1'

services:
  app:
    container_name: app
    image: 'expense-tracker-api:latest'
    build: ./
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expensetrackerdb
      - SPRING_DATASOURCE_USERNAME=expense_tracker
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=expense_tracker
      - POSTGRES_PASSWORD=password